estudiantes = [
    "Ana",
    "Luis",
    "Pedro",
    "María",
    "Carlos",
    "Sofía",
    "Diego",
    "Valeria",
    "José",
    "Camila",
    "Andrés",
    "Lucía",
    "Miguel",
    "Daniela",
    "Javier",
    "Paula",
    "Fernando",
    "Alejandra",
    "Ricardo",
    "Gabriela",
    "Jhontan",
    "Ramirez",
    "Villalta",
    "Vera",
    "Bances",
    "Niño",
    "Lupaca",
    "Tirado",
    "Cerasuolo",
    "Gustavo",
    "Lozano",
    "Erick",
]

herramientas = [
    "Visual Studio Code",
    "PyCharm",
    "Jupyter Notebook",
    "Git",
    "GitHub",
    "Docker",
    "Kubernetes",
    "Postman",
    "Figma",
    "Canva",
    "Google Drive",
    "Microsoft Excel",
    "Microsoft Word",
    "Power BI",
    "Tableau",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "SQLite",
    "Oracle Database",
    "Python",
    "Java",
    "C++",
    "JavaScript",
    "HTML",
    "CSS",
    "React",
    "Angular",
    "Node.js",
    "Django",
]
